namespace KHCT.Application.Tasks;

public record TaskListItemDto(
    Guid Id,
    Guid PlanId,
    Guid? ParentTaskId,
    string? OutlineIndex,
    int DisplayOrder,
    bool IsHeader,
    string Title,
    int WorkType,
    string WorkStatus,
    DateTime? Deadline,
    Guid? AssigneeUserId,
    string? AssigneeName,
    Guid? OwnerDepartmentId,
    string? OwnerDepartmentCode,
    string? OwnerDepartmentName,
    string? BksMemberText,
    string? KtnbLeaderText,
    string? NoteText,
    bool IsLocked,
    bool HasOpenComment,
    string ApprovalStatus,
    DateTime? SubmittedAt,
    DateTime? ApprovedAt,
    string? ProgressText,
    string? ReasonNotCompleted,
    IReadOnlyList<Guid> SupportingDepartmentIds,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public record SupportingDepartmentDto(Guid Id, string Code, string Name);

public record TaskDetailDto(
    Guid Id,
    Guid PlanId,
    Guid? ParentTaskId,
    string? OutlineIndex,
    int DisplayOrder,
    bool IsHeader,
    string Title,
    int WorkType,
    string WorkStatus,
    DateTime? Deadline,
    Guid? AssigneeUserId,
    string? AssigneeName,
    Guid? OwnerDepartmentId,
    string? OwnerDepartmentCode,
    string? OwnerDepartmentName,
    string? BksMemberText,
    string? KtnbLeaderText,
    string? NoteText,
    bool IsLocked,
    bool HasOpenComment,
    string ApprovalStatus,
    DateTime? SubmittedAt,
    DateTime? ApprovedAt,
    string? ProgressText,
    string? ReasonNotCompleted,
    IReadOnlyList<SupportingDepartmentDto> SupportingDepartments,
    DateTime CreatedAt,
    DateTime UpdatedAt);
